# Generated by Django 3.0.2 on 2020-01-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(default='Collection', max_length=100)),
                ('text2', models.CharField(default='New arrivals', max_length=100)),
                ('slideimage', models.ImageField(default='uploadback.jpeg', upload_to='sliderimage')),
                ('thumbnail', models.ImageField(default='uploadback.jpeg', upload_to='sliderimage')),
                ('thumbcaption', models.CharField(default='Visit Shop', max_length=30)),
            ],
        ),
    ]
