# Generated by Django 3.0.2 on 2020-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='slideimage',
            field=models.ImageField(default='sliderimage/uploadback.jpeg', upload_to='sliderimage'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='thumbnail',
            field=models.ImageField(default='sliderimage/uploadback.jpeg', upload_to='sliderimage'),
        ),
    ]
