# Generated by Django 3.0.2 on 2020-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200112_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='product name', max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('bag', 'Bag'), ('shoes', 'Shoes'), ('watches', 'Watches')], default='*', max_length=100)),
                ('item_feature', models.CharField(default='No Feature Mention', max_length=100)),
                ('item_description', models.CharField(default='No Description', max_length=600)),
                ('additional_info_weight', models.CharField(default='..kg', max_length=10)),
                ('additional_info_dimensions', models.CharField(default='.x.x.x cm', max_length=20)),
                ('additional_info_material', models.CharField(default='..% cotton', max_length=50)),
                ('additional_info_available_color', models.CharField(default='black,red,grey....', max_length=100)),
                ('additional_info_size', models.CharField(default='S,M,L,XL,XXL', max_length=50)),
                ('item_image', models.ImageField(default=False, upload_to='productImages')),
                ('item_Back_view', models.ImageField(default=True, upload_to='productImages')),
                ('item_alone_view', models.ImageField(default=True, upload_to='productImage')),
            ],
        ),
    ]
