# Generated by Django 3.0.2 on 2020-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_price',
            field=models.IntegerField(default='Rs.00'),
        ),
    ]
