# Generated by Django 3.0.2 on 2020-01-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200113_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='slideimage',
            field=models.ImageField(default=False, upload_to='sliderimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_Back_view',
            field=models.ImageField(upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_alone_view',
            field=models.ImageField(upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(upload_to='productImages'),
        ),
    ]
