# Generated by Django 3.0.2 on 2020-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='slideimage',
            field=models.ImageField(upload_to='sliderimage'),
        ),
    ]
