# Generated by Django 3.0.2 on 2020-01-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200113_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='productcollectioninfo',
        ),
    ]
