# Generated by Django 3.0.2 on 2020-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200113_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollectioninfo',
            name='item_description',
            field=models.TextField(default='No Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productcollectioninfo',
            name='item_feature',
            field=models.TextField(default='No Feature Mention', max_length=100),
        ),
    ]
