# Generated by Django 3.0.2 on 2020-01-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200115_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopaddress', models.CharField(default='address', max_length=200)),
                ('shopphone', models.IntegerField()),
                ('shopgmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
