# Generated by Django 3.0.2 on 2020-01-17 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 10, 52, 19, 934812)),
        ),
    ]
