# Generated by Django 3.0.2 on 2020-01-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200117_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='webabout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=100)),
                ('about_para1', models.CharField(max_length=100)),
                ('about_para2', models.CharField(blank=True, max_length=100)),
                ('about_image', models.ImageField(upload_to='about_images')),
                ('about_theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 18, 49, 20, 792613)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
