# Generated by Django 3.0.2 on 2020-01-18 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200118_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 18, 59, 41, 836014)),
        ),
        migrations.AlterField(
            model_name='webabout',
            name='about_para1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='webabout',
            name='about_para2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='webabout',
            name='about_theme',
            field=models.TextField(max_length=300),
        ),
    ]
