# Generated by Django 3.0.2 on 2020-01-19 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200119_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 20, 8, 0, 32749)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.TextField(max_length=5000),
        ),
    ]
