# Generated by Django 3.0.2 on 2020-01-20 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200120_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 13, 17, 52, 812573)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewsms',
            field=models.TextField(max_length=1000),
        ),
    ]
