# Generated by Django 3.0.2 on 2020-01-23 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200123_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 20, 9, 47, 972369)),
        ),
    ]
