# Generated by Django 3.0.2 on 2020-01-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 21, 55, 58, 831911)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.TextField(max_length=5000),
        ),
    ]
